---
name: NoBodyOnline
Author: dsate1/GracieWargo
description: Just sends a message back to the player!
version: 1.0.0
api: [1.12.0]
main: NoBodyOnline/Main

commands: 
      Hello: 
        description: Sends a message to the user.
        permission: Hello.cmd
permissions:
      default: true
      description: "Sends a message to the user"
